# Necessary Imports

In [1]:
import pandas as pd
import numpy as np

# Loading Data

In [2]:
df = pd.read_csv('kidney_disease.csv')
df.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

In [3]:
df['age'].mean()

51.48337595907928

In [4]:
df.shape

(400, 26)

# Dropping id Column

In [5]:
df.drop('id',axis=1,inplace=True)

In [6]:
df.head()

age    bp     sg   al   su     rbc        pc         pcc          ba  \
0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

     bgr  ...  pcv    wc   rc  htn   dm cad appet   pe  ane classification  
0  121.0  ...   44  7800  5.2  yes  yes  no  good   no   no            ckd  
1    NaN  ...   38  6000  NaN   no   no  no  good   no   no            ckd  
2  423.0  ...   31  7500  NaN   no  yes  no  poor   no  yes            ckd  
3  117.0  ...   32  6700  3.9  yes   no  no  poor  yes  yes            ckd  
4  106.0  ...   35  7300  4.6   no   no  no  good   no   no            ckd  

[5 rows x 25 columns]

In [7]:
df.describe()

age          bp          sg          al          su         bgr  \
count  391.000000  388.000000  353.000000  354.000000  351.000000  356.000000   
mean    51.483376   76.469072    1.017408    1.016949    0.450142  148.036517   
std     17.169714   13.683637    0.005717    1.352679    1.099191   79.281714   
min      2.000000   50.000000    1.005000    0.000000    0.000000   22.000000   
25%     42.000000   70.000000    1.010000    0.000000    0.000000   99.000000   
50%     55.000000   80.000000    1.020000    0.000000    0.000000  121.000000   
75%     64.500000   80.000000    1.020000    2.000000    0.000000  163.000000   
max     90.000000  180.000000    1.025000    5.000000    5.000000  490.000000   

               bu          sc         sod         pot        hemo  
count  381.000000  383.000000  313.000000  312.000000  348.000000  
mean    57.425722    3.072454  137.528754    4.627244   12.526437  
std     50.503006    5.741126   10.408752    3.193904    2.912587  
min      1.500000    0.400000    4.500000    2.500000    3.100000  
25%     27.000000    0.900000  135.000000    3.800000   10.300000  
50%     42.000000    1.300000  138.000000    4.400000   12.650000  
75%     66.000000    2.800000  142.000000    4.900000   15.000000  
max    391.000000   76.000000  163.000000   47.000000   17.800000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             330 non-null    object 
 16  wc              295 non-null    object 
 17  rc              270 non-null    obj

# Convert into Numeric Dtype

In [10]:
df['pcv'] = pd.to_numeric(df['pcv'],errors = 'coerce')
df['wc'] = pd.to_numeric(df['wc'],errors = 'coerce')
df['rc'] = pd.to_numeric(df['rc'],errors = 'coerce')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             329 non-null    float64
 16  wc              294 non-null    float64
 17  rc              269 non-null    flo

# **Extracting Categorical**

In [12]:
cat_cols = [col for col in df.columns if df[col].dtype == 'object']
cat_cols

['rbc',
 'pc',
 'pcc',
 'ba',
 'htn',
 'dm',
 'cad',
 'appet',
 'pe',
 'ane',
 'classification']

# **Extracting Numerical**

In [13]:
num_cols = [col for col in df.columns if df[col].dtype != 'object']
num_cols

['age',
 'bp',
 'sg',
 'al',
 'su',
 'bgr',
 'bu',
 'sc',
 'sod',
 'pot',
 'hemo',
 'pcv',
 'wc',
 'rc']

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             391 non-null    float64
 1   bp              388 non-null    float64
 2   sg              353 non-null    float64
 3   al              354 non-null    float64
 4   su              351 non-null    float64
 5   rbc             248 non-null    object 
 6   pc              335 non-null    object 
 7   pcc             396 non-null    object 
 8   ba              396 non-null    object 
 9   bgr             356 non-null    float64
 10  bu              381 non-null    float64
 11  sc              383 non-null    float64
 12  sod             313 non-null    float64
 13  pot             312 non-null    float64
 14  hemo            348 non-null    float64
 15  pcv             329 non-null    float64
 16  wc              294 non-null    float64
 17  rc              269 non-null    flo

# Get unique values from categorical columns

In [15]:
for col in cat_cols:
  print(f"{col} ---> {df[col].unique()} values")

rbc ---> [nan 'normal' 'abnormal'] values
pc ---> ['normal' 'abnormal' nan] values
pcc ---> ['notpresent' 'present' nan] values
ba ---> ['notpresent' 'present' nan] values
htn ---> ['yes' 'no' nan] values
dm ---> ['yes' 'no' ' yes' '\tno' '\tyes' nan] values
cad ---> ['no' 'yes' '\tno' nan] values
appet ---> ['good' 'poor' nan] values
pe ---> ['no' 'yes' nan] values
ane ---> ['no' 'yes' nan] values
classification ---> ['ckd' 'ckd\t' 'notckd'] values


# Remove Ambiguity

In [16]:
df['dm'].replace(to_replace={'\tno' : 'no','\tyes':'yes','yes':'yes',' yes':'yes'},inplace=True)
df['cad'].replace(to_replace={'\tno' : 'no','\tyes':'yes','yes':'yes',' yes':'yes'},inplace=True)
df['classification'].replace(to_replace={'ckd\t' : 'ckd','notckd':'notckd'},inplace=True)

# Convert categorical to numeric

In [18]:
#df['classification'] = df['classification'].map()
df['classification'].replace(to_replace={'ckd':0,'notckd':1},inplace=True)
#df['classification'] = pd.to_numeric(df['classification'],errors='coerce')

In [19]:
df['classification']

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    1
399    1
Name: classification, Length: 400, dtype: int64

In [20]:

for col in cat_cols:
  print(f"{col} ---> {df[col].unique()} values")

rbc ---> [nan 'normal' 'abnormal'] values
pc ---> ['normal' 'abnormal' nan] values
pcc ---> ['notpresent' 'present' nan] values
ba ---> ['notpresent' 'present' nan] values
htn ---> ['yes' 'no' nan] values
dm ---> ['yes' 'no' nan] values
cad ---> ['no' 'yes' nan] values
appet ---> ['good' 'poor' nan] values
pe ---> ['no' 'yes' nan] values
ane ---> ['no' 'yes' nan] values
classification ---> [0 1] values


In [21]:

for col in num_cols:
  print(f"{col} ---> {df[col].unique()} values")

age ---> [48.  7. 62. 51. 60. 68. 24. 52. 53. 50. 63. 40. 47. 61. 21. 42. 75. 69.
 nan 73. 70. 65. 76. 72. 82. 46. 45. 35. 54. 11. 59. 67. 15. 55. 44. 26.
 64. 56.  5. 74. 38. 58. 71. 34. 17. 12. 43. 41. 57.  8. 39. 66. 81. 14.
 27. 83. 30.  4.  3.  6. 32. 80. 49. 90. 78. 19.  2. 33. 36. 37. 23. 25.
 20. 29. 28. 22. 79.] values
bp ---> [ 80.  50.  70.  90.  nan 100.  60. 110. 140. 180. 120.] values
sg ---> [1.02  1.01  1.005 1.015   nan 1.025] values
al ---> [ 1.  4.  2.  3.  0. nan  5.] values
su ---> [ 0.  3.  4.  1. nan  2.  5.] values
bgr ---> [121.  nan 423. 117. 106.  74. 100. 410. 138.  70. 490. 380. 208.  98.
 157.  76.  99. 114. 263. 173.  95. 108. 156. 264. 123.  93. 107. 159.
 140. 171. 270.  92. 137. 204.  79. 207. 124. 144.  91. 162. 246. 253.
 141. 182.  86. 150. 146. 425. 112. 250. 360. 163. 129. 133. 102. 158.
 165. 132. 104. 127. 415. 169. 251. 109. 280. 210. 219. 295.  94. 172.
 101. 298. 153.  88. 226. 143. 115.  89. 297. 233. 294. 323. 125.  90.
 308. 118. 224. 128.

# **Data Pre Processing**

In [22]:
df.isna().sum().sort_values(ascending=False)

rbc               152
rc                131
wc                106
pot                88
sod                87
pcv                71
pc                 65
hemo               52
su                 49
sg                 47
al                 46
bgr                44
bu                 19
sc                 17
bp                 12
age                 9
ba                  4
pcc                 4
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [23]:
df[num_cols].isnull().sum()

age       9
bp       12
sg       47
al       46
su       49
bgr      44
bu       19
sc       17
sod      87
pot      88
hemo     52
pcv      71
wc      106
rc      131
dtype: int64

# **Filling Null Values for categorical data**




In [24]:
for col in cat_cols:
  print(f"{col} ---> {df[col].unique()} values")

rbc ---> [nan 'normal' 'abnormal'] values
pc ---> ['normal' 'abnormal' nan] values
pcc ---> ['notpresent' 'present' nan] values
ba ---> ['notpresent' 'present' nan] values
htn ---> ['yes' 'no' nan] values
dm ---> ['yes' 'no' nan] values
cad ---> ['no' 'yes' nan] values
appet ---> ['good' 'poor' nan] values
pe ---> ['no' 'yes' nan] values
ane ---> ['no' 'yes' nan] values
classification ---> [0 1] values


In [25]:
for col in cat_cols:
  mode = df[col].mode()[0]
  df[col] = df[col].fillna(mode)


df[cat_cols]

rbc        pc         pcc          ba  htn   dm cad appet   pe  ane  \
0    normal    normal  notpresent  notpresent  yes  yes  no  good   no   no   
1    normal    normal  notpresent  notpresent   no   no  no  good   no   no   
2    normal    normal  notpresent  notpresent   no  yes  no  poor   no  yes   
3    normal  abnormal     present  notpresent  yes   no  no  poor  yes  yes   
4    normal    normal  notpresent  notpresent   no   no  no  good   no   no   
..      ...       ...         ...         ...  ...  ...  ..   ...  ...  ...   
395  normal    normal  notpresent  notpresent   no   no  no  good   no   no   
396  normal    normal  notpresent  notpresent   no   no  no  good   no   no   
397  normal    normal  notpresent  notpresent   no   no  no  good   no   no   
398  normal    normal  notpresent  notpresent   no   no  no  good   no   no   
399  normal    normal  notpresent  notpresent   no   no  no  good   no   no   

     classification  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
395               1  
396               1  
397               1  
398               1  
399               1  

[400 rows x 11 columns]

In [26]:
for col in cat_cols:
  print(f"{col} ---> {df[col].unique()} values")

rbc ---> ['normal' 'abnormal'] values
pc ---> ['normal' 'abnormal'] values
pcc ---> ['notpresent' 'present'] values
ba ---> ['notpresent' 'present'] values
htn ---> ['yes' 'no'] values
dm ---> ['yes' 'no'] values
cad ---> ['no' 'yes'] values
appet ---> ['good' 'poor'] values
pe ---> ['no' 'yes'] values
ane ---> ['no' 'yes'] values
classification ---> [0 1] values


# **Filling Null Values for Numeric Data**

In [27]:
for col in num_cols:
  print(f"{col} ---> {df[col].unique()} values")

age ---> [48.  7. 62. 51. 60. 68. 24. 52. 53. 50. 63. 40. 47. 61. 21. 42. 75. 69.
 nan 73. 70. 65. 76. 72. 82. 46. 45. 35. 54. 11. 59. 67. 15. 55. 44. 26.
 64. 56.  5. 74. 38. 58. 71. 34. 17. 12. 43. 41. 57.  8. 39. 66. 81. 14.
 27. 83. 30.  4.  3.  6. 32. 80. 49. 90. 78. 19.  2. 33. 36. 37. 23. 25.
 20. 29. 28. 22. 79.] values
bp ---> [ 80.  50.  70.  90.  nan 100.  60. 110. 140. 180. 120.] values
sg ---> [1.02  1.01  1.005 1.015   nan 1.025] values
al ---> [ 1.  4.  2.  3.  0. nan  5.] values
su ---> [ 0.  3.  4.  1. nan  2.  5.] values
bgr ---> [121.  nan 423. 117. 106.  74. 100. 410. 138.  70. 490. 380. 208.  98.
 157.  76.  99. 114. 263. 173.  95. 108. 156. 264. 123.  93. 107. 159.
 140. 171. 270.  92. 137. 204.  79. 207. 124. 144.  91. 162. 246. 253.
 141. 182.  86. 150. 146. 425. 112. 250. 360. 163. 129. 133. 102. 158.
 165. 132. 104. 127. 415. 169. 251. 109. 280. 210. 219. 295.  94. 172.
 101. 298. 153.  88. 226. 143. 115.  89. 297. 233. 294. 323. 125.  90.
 308. 118. 224. 128.

In [28]:
df[num_cols].isnull().sum()

age       9
bp       12
sg       47
al       46
su       49
bgr      44
bu       19
sc       17
sod      87
pot      88
hemo     52
pcv      71
wc      106
rc      131
dtype: int64

In [29]:
df['age'].mean()

51.48337595907928

In [30]:
for col in num_cols:
  mean_sample = df[col].mean()
  df.loc[df[col].isnull(),col] = mean_sample

In [31]:
#df[num_cols].isnull().sum()

In [32]:
df['age'].mean()

51.483375959079275

In [35]:
df[num_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     400 non-null    float64
 1   bp      400 non-null    float64
 2   sg      400 non-null    float64
 3   al      400 non-null    float64
 4   su      400 non-null    float64
 5   bgr     400 non-null    float64
 6   bu      400 non-null    float64
 7   sc      400 non-null    float64
 8   sod     400 non-null    float64
 9   pot     400 non-null    float64
 10  hemo    400 non-null    float64
 11  pcv     400 non-null    float64
 12  wc      400 non-null    float64
 13  rc      400 non-null    float64
dtypes: float64(14)
memory usage: 43.9 KB


# **Feature Encoding**

In [36]:
for col in cat_cols:
  print("{} has {} categories \n" .format(col,df[col].unique()))
  print("{} has {} categories \n" .format(col,df[col].nunique()))

rbc has ['normal' 'abnormal'] categories 

rbc has 2 categories 

pc has ['normal' 'abnormal'] categories 

pc has 2 categories 

pcc has ['notpresent' 'present'] categories 

pcc has 2 categories 

ba has ['notpresent' 'present'] categories 

ba has 2 categories 

htn has ['yes' 'no'] categories 

htn has 2 categories 

dm has ['yes' 'no'] categories 

dm has 2 categories 

cad has ['no' 'yes'] categories 

cad has 2 categories 

appet has ['good' 'poor'] categories 

appet has 2 categories 

pe has ['no' 'yes'] categories 

pe has 2 categories 

ane has ['no' 'yes'] categories 

ane has 2 categories 

classification has [0 1] categories 

classification has 2 categories 



In [37]:
from sklearn.preprocessing import LabelEncoder
le_obj = LabelEncoder()

for col in cat_cols:
  df[col] = le_obj.fit_transform(df[col])


In [38]:
for col in cat_cols:
  print("{} has {} categories \n" .format(col,df[col].unique()))
 # print("{} has {} categories \n" .format(col,df[col].nunique()))

rbc has [1 0] categories 

pc has [1 0] categories 

pcc has [0 1] categories 

ba has [0 1] categories 

htn has [1 0] categories 

dm has [1 0] categories 

cad has [0 1] categories 

appet has [0 1] categories 

pe has [0 1] categories 

ane has [0 1] categories 

classification has [0 1] categories 



In [39]:
df[cat_cols].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rbc             400 non-null    int32
 1   pc              400 non-null    int32
 2   pcc             400 non-null    int32
 3   ba              400 non-null    int32
 4   htn             400 non-null    int32
 5   dm              400 non-null    int32
 6   cad             400 non-null    int32
 7   appet           400 non-null    int32
 8   pe              400 non-null    int32
 9   ane             400 non-null    int32
 10  classification  400 non-null    int64
dtypes: int32(10), int64(1)
memory usage: 18.9 KB


# **Build the Model**

**Classify input Features and target feature**

In [40]:
df.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [41]:
len(df.columns)

25

In [42]:
df['classification']

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    1
399    1
Name: classification, Length: 400, dtype: int64

In [43]:
input_col = df.columns[0:24]
target_col = 'classification'



In [44]:
X = df[input_col]
Y = df[target_col]

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,Y_test = train_test_split(
    X,
    Y,
    test_size = 0.30,
    random_state=1


)

In [46]:
X_train

age    bp        sg        al        su  rbc  pc  pcc  ba         bgr  \
39   82.0  80.0  1.010000  2.000000  2.000000    1   1    0   0  140.000000   
167  34.0  70.0  1.020000  0.000000  0.000000    0   1    0   0  139.000000   
383  80.0  80.0  1.025000  0.000000  0.000000    1   1    0   0  119.000000   
221  66.0  70.0  1.020000  1.000000  0.000000    1   1    0   0  248.000000   
351  29.0  80.0  1.020000  0.000000  0.000000    1   1    0   0   83.000000   
..    ...   ...       ...       ...       ...  ...  ..  ...  ..         ...   
255  34.0  80.0  1.025000  0.000000  0.000000    1   1    0   0  121.000000   
72   64.0  90.0  1.010000  3.000000  3.000000    1   0    1   0  148.036517   
396  42.0  70.0  1.025000  0.000000  0.000000    1   1    0   0   75.000000   
235  45.0  70.0  1.010000  2.000000  0.000000    1   1    0   0  113.000000   
37   72.0  80.0  1.017408  1.016949  0.450142    1   1    0   0  137.000000   

     ...       hemo        pcv           wc        rc  htn  dm  cad  appet  \
39   ...  13.000000  40.000000  9800.000000  4.200000    1   1    0      0   
167  ...  12.700000  42.000000  2200.000000  4.707435    0   0    0      1   
383  ...  13.900000  49.000000  5100.000000  5.000000    0   0    0      0   
221  ...  12.526437  38.884498  8406.122449  4.707435    1   1    0      0   
351  ...  17.500000  40.000000  9900.000000  4.700000    0   0    0      0   
..   ...        ...        ...          ...       ...  ...  ..  ...    ...   
255  ...  13.600000  52.000000  9200.000000  6.300000    0   0    0      0   
72   ...  10.300000  38.884498  8406.122449  4.707435    1   1    0      0   
396  ...  16.500000  54.000000  7800.000000  6.200000    0   0    0      0   
235  ...   7.900000  26.000000  5700.000000  4.707435    0   0    1      0   
37   ...   9.700000  28.000000  6900.000000  2.500000    1   1    0      1   

     pe  ane  
39    0    0  
167   0    0  
383   0    0  
221   0    0  
351   0    0  
..   ..  ...  
255   0    0  
72    1    0  
396   0    0  
235   0    1  
37    0    1  

[280 rows x 24 columns]

In [47]:
X_test

age    bp        sg        al        su  rbc  pc  pcc  ba         bgr  \
398  17.0  60.0  1.025000  0.000000  0.000000    1   1    0   0  114.000000   
125  72.0  90.0  1.017408  1.016949  0.450142    1   1    0   0  308.000000   
328  28.0  70.0  1.020000  0.000000  0.000000    1   1    0   0  131.000000   
339  25.0  70.0  1.020000  0.000000  0.000000    1   1    0   0   88.000000   
172  62.0  80.0  1.010000  1.000000  2.000000    1   1    0   0  309.000000   
..    ...   ...       ...       ...       ...  ...  ..  ...  ..         ...   
91   56.0  70.0  1.015000  4.000000  1.000000    0   1    0   0  210.000000   
322  70.0  60.0  1.017408  1.016949  0.450142    1   1    0   0  120.000000   
248  59.0  70.0  1.010000  1.000000  3.000000    0   0    0   0  424.000000   
186   8.0  50.0  1.020000  4.000000  0.000000    1   1    0   0  148.036517   
395  55.0  80.0  1.020000  0.000000  0.000000    1   1    0   0  140.000000   

     ...       hemo        pcv            wc        rc  htn  dm  cad  appet  \
398  ...  14.200000  51.000000   7200.000000  5.900000    0   0    0      0   
125  ...  12.526437  38.884498   8406.122449  4.707435    1   1    0      1   
328  ...  12.526437  45.000000   8600.000000  6.500000    0   0    0      0   
339  ...  13.300000  48.000000   7000.000000  4.900000    0   0    0      0   
172  ...  10.600000  34.000000  12800.000000  4.900000    0   0    0      0   
..   ...        ...        ...           ...       ...  ...  ..  ...    ...   
91   ...  16.100000  52.000000  12500.000000  5.600000    0   0    0      0   
322  ...  16.000000  43.000000   4500.000000  4.900000    0   0    0      0   
248  ...  12.600000  37.000000  10200.000000  4.100000    1   1    1      0   
186  ...  12.526437  38.884498   8406.122449  4.707435    0   0    0      0   
395  ...  15.700000  47.000000   6700.000000  4.900000    0   0    0      0   

     pe  ane  
398   0    0  
125   0    0  
328   0    0  
339   0    0  
172   0    0  
..   ..  ...  
91    0    0  
322   0    0  
248   0    0  
186   1    0  
395   0    0  

[120 rows x 24 columns]

In [48]:
Y_train

39     0
167    0
383    1
221    0
351    1
      ..
255    1
72     0
396    1
235    0
37     0
Name: classification, Length: 280, dtype: int64

In [49]:
Y_test

398    1
125    0
328    1
339    1
172    0
      ..
91     0
322    1
248    0
186    0
395    1
Name: classification, Length: 120, dtype: int64

# **Decision Tree Classifier**

**Neccesary imports**

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

In [51]:
help(DecisionTreeClassifier)

Help on class DecisionTreeClassifier in module sklearn.tree._classes:

class DecisionTreeClassifier(sklearn.base.ClassifierMixin, BaseDecisionTree)
 |  DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)
 |  
 |  A decision tree classifier.
 |  
 |  Read more in the :ref:`User Guide <tree>`.
 |  
 |  Parameters
 |  ----------
 |  criterion : {"gini", "entropy", "log_loss"}, default="gini"
 |      The function to measure the quality of a split. Supported criteria are
 |      "gini" for the Gini impurity and "log_loss" and "entropy" both for the
 |      Shannon information gain, see :ref:`tree_mathematical_formulation`.
 |  
 |  splitter : {"best", "random"}, default="best"
 |      The strategy used to choose the split at each node. Supported
 |      strategies are "best" to 

# Model

In [52]:
dt = DecisionTreeClassifier()
dt.fit(X_train,Y_train)

DecisionTreeClassifier()

# Prediction

In [53]:
X_test_pred = dt.predict(X_test)

In [54]:
X_train_pred = dt.predict(X_train)

# Testing Data Accuracy

In [55]:
np.mean(Y_test == X_test_pred) *100

95.83333333333334

In [56]:
dt_test_acc = accuracy_score(Y_test,X_test_pred)
dt_test_acc*100

95.83333333333334

# Training Data Accuracy

In [57]:
np.mean(Y_train == X_train_pred) *100

100.0

In [58]:
dt_train_acc = accuracy_score(Y_train,X_train_pred)
dt_train_acc*100

100.0

# Classification Report

In [59]:
print(classification_report(Y_test,X_test_pred))

              precision    recall  f1-score   support

           0       0.97      0.96      0.96        70
           1       0.94      0.96      0.95        50

    accuracy                           0.96       120
   macro avg       0.96      0.96      0.96       120
weighted avg       0.96      0.96      0.96       120



# Model with Entropy criterion

In [60]:
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy')

In [61]:
X_train_pred = dt.predict(X_train)

In [62]:
X_test_pred = dt.predict(X_test)

# Test Data Accuracy

In [63]:
np.mean(Y_test == X_test_pred) *100

99.16666666666667

In [64]:
dt_test_acc = accuracy_score(Y_test,X_test_pred)
dt_test_acc*100

99.16666666666667

# Train Data Accuracy

In [65]:
np.mean(Y_train == X_train_pred) *100

100.0

In [66]:
dt_train_acc = accuracy_score(Y_train,X_train_pred)
dt_train_acc*100

100.0

# Classification Report

In [67]:
print(classification_report(Y_test,X_test_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        70
           1       0.98      1.00      0.99        50

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



# Hyper Parameter tuning

In [68]:
from sklearn.model_selection import GridSearchCV
#dir(model_selection)

In [69]:
help(GridSearchCV)

Help on class GridSearchCV in module sklearn.model_selection._search:

class GridSearchCV(BaseSearchCV)
 |  GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)
 |  
 |  Exhaustive search over specified parameter values for an estimator.
 |  
 |  Important members are fit, predict.
 |  
 |  GridSearchCV implements a "fit" and a "score" method.
 |  It also implements "score_samples", "predict", "predict_proba",
 |  "decision_function", "transform" and "inverse_transform" if they are
 |  implemented in the estimator used.
 |  
 |  The parameters of the estimator used to apply these methods are optimized
 |  by cross-validated grid-search over a parameter grid.
 |  
 |  Read more in the :ref:`User Guide <grid_search>`.
 |  
 |  Parameters
 |  ----------
 |  estimator : estimator object
 |      This is assumed to implement the scikit-learn estimator interface.
 |      Either est

In [70]:
help(DecisionTreeClassifier)

Help on class DecisionTreeClassifier in module sklearn.tree._classes:

class DecisionTreeClassifier(sklearn.base.ClassifierMixin, BaseDecisionTree)
 |  DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)
 |  
 |  A decision tree classifier.
 |  
 |  Read more in the :ref:`User Guide <tree>`.
 |  
 |  Parameters
 |  ----------
 |  criterion : {"gini", "entropy", "log_loss"}, default="gini"
 |      The function to measure the quality of a split. Supported criteria are
 |      "gini" for the Gini impurity and "log_loss" and "entropy" both for the
 |      Shannon information gain, see :ref:`tree_mathematical_formulation`.
 |  
 |  splitter : {"best", "random"}, default="best"
 |      The strategy used to choose the split at each node. Supported
 |      strategies are "best" to 

# Hyper Parameter Tuning of DecisionTree

In [71]:
dt_params = {
    'criterion' :['gini','entropy'],
    'max_depth' : [3,5,7,10],
    'splitter' : ['best','random'],
    'min_samples_leaf':[1,2,3,5,7],
    'min_samples_split':[1,2,3,5,7],
    'max_features' : ['auto','sqrt','log2']
}

In [72]:
gs_dt = GridSearchCV(
    dt,
    dt_params,
    cv = 5,
    n_jobs = -1,
    verbose=1

)

gs_dt.fit(X_train,Y_train)

Fitting 5 folds for each of 1200 candidates, totalling 6000 fits


c:\Users\prave\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
2800 fits failed out of a total of 6000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1059 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\prave\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\prave\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\prave\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\b

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(criterion='entropy'),
             n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 7, 10],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 3, 5, 7],
                         'min_samples_split': [1, 2, 3, 5, 7],
                         'splitter': ['best', 'random']},
             verbose=1)

In [73]:
gs_dt.best_params_

{'criterion': 'entropy',
 'max_depth': 10,
 'max_features': 'log2',
 'min_samples_leaf': 1,
 'min_samples_split': 7,
 'splitter': 'random'}

In [74]:
gs_dt.best_score_

0.9857142857142855

In [75]:
gs_dt.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=10, max_features='log2',
                       min_samples_split=7, splitter='random')

In [76]:
accuracy_score(Y_train,X_train_pred)

1.0

In [77]:
accuracy_score(Y_test,X_test_pred)

0.9916666666666667

In [78]:
confusion_matrix(Y_test,dt.predict(X_test))

array([[69,  1],
       [ 0, 50]], dtype=int64)

In [79]:
confusion_matrix(Y_train,dt.predict(X_train))

array([[180,   0],
       [  0, 100]], dtype=int64)

In [80]:
print(classification_report(Y_test,dt.predict(X_test)))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        70
           1       0.98      1.00      0.99        50

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



# Bagging

**Random Forest Classifier**

In [81]:
from sklearn.ensemble import RandomForestClassifier

In [82]:
rf = RandomForestClassifier(n_jobs=3,oob_score=True,n_estimators=50,criterion="entropy")
rf.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=50, n_jobs=3,
                       oob_score=True)

In [83]:
print( "Testing Data Accuracy " ,accuracy_score(Y_test,rf.predict(X_test)))

Testing Data Accuracy  0.9833333333333333


In [84]:
print( "Training Data Accuracy " ,accuracy_score(Y_train,rf.predict(X_train)))

Training Data Accuracy  1.0


In [85]:
confusion_matrix(Y_test,rf.predict(X_test))

array([[69,  1],
       [ 1, 49]], dtype=int64)

In [86]:
print(classification_report(Y_test,rf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99        70
           1       0.98      0.98      0.98        50

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120



# **Ada Boost Classifier**

In [87]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score

In [88]:
clf = AdaBoostClassifier(n_estimators=100)

In [89]:
clf.fit(X_train,Y_train)

AdaBoostClassifier(n_estimators=100)

In [90]:
pred = clf.predict(X)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [91]:
clf.score(X_test, Y_test)

0.9833333333333333

# **Logistic Regression**

In [92]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(X_train, Y_train)

c:\Users\prave\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [93]:
#Predicting the test set result
y_pred= classifier.predict(X_test)

In [94]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,Y_test),'\n')

              precision    recall  f1-score   support

           0       0.89      0.91      0.90        68
           1       0.88      0.85      0.86        52

    accuracy                           0.88       120
   macro avg       0.88      0.88      0.88       120
weighted avg       0.88      0.88      0.88       120
 



# **Naive Bayes**

In [95]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [115]:
imnb = MultinomialNB()

In [116]:
pred_mnb = imnb.fit(X_train,Y_train) 

In [117]:
Y_train_pred = pred_mnb.predict(X_train)
Y_train_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [118]:
confusion_matrix(Y_train,Y_train_pred)

array([[139,  41],
       [  4,  96]], dtype=int64)

In [119]:
accuracy_score(Y_train,Y_train_pred)

0.8392857142857143

In [120]:
Y_pred = pred_mnb.predict(X_test)
Y_pred

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [121]:
accuracy_score(Y_test,Y_pred) 

0.8583333333333333

# **KNN**

In [96]:
from sklearn.neighbors import KNeighborsClassifier as KNC

In [97]:
neigh = KNC(n_neighbors= 3)
neigh

KNeighborsClassifier(n_neighbors=3)

In [98]:
neigh.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3)

In [99]:
train_pred=neigh.predict(X_train)
train_pred

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [104]:
train_acc = np.mean(neigh.predict(X_train)==(Y_train))
print(train_acc*100)

90.35714285714286


In [109]:
test_acc = np.mean(neigh.predict(X_test)==(Y_test))
print(test_acc*100)

75.83333333333333


In [110]:
# for 5 nearest neighbours
neigh = KNC(n_neighbors=5)
neigh

KNeighborsClassifier()

In [111]:
neigh.fit(X_train,Y_train)

KNeighborsClassifier()

In [112]:
train_pred=neigh.predict(X_train)
train_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [113]:
train_acc = np.mean(neigh.predict(X_train)==(Y_train))
print(train_acc*100)

81.07142857142857


In [114]:
test_acc = np.mean(neigh.predict(X_test)==(Y_test))
print(test_acc*100)

78.33333333333333
