                                                        Applying the SVM 

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('User_Data.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dummy_gender = pd.get_dummies(df['Gender'], prefix='Gender')

# Concatenate the dummy variables with the original DataFrame
df = pd.concat([df, dummy_gender], axis=1)

# Drop the original "Gender" column if needed
df.drop('Gender', axis=1, inplace=True)
df

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0          False         True
1    15810944   35            20000          0          False         True
2    15668575   26            43000          0           True        False
3    15603246   27            57000          0           True        False
4    15804002   19            76000          0          False         True
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1           True        False
396  15706071   51            23000          1          False         True
397  15654296   50            20000          1           True        False
398  15755018   36            33000          0          False         True
399  15594041   49            36000          1           True        False

[400 rows x 6 columns]

                                                            REPLACING MALE WITH 1 AND FEMALE WIHT 0

In [4]:
df['Gender_Male'] = df['Gender_Male'].replace({True:1, False: 0})
df['Gender_Female'] = df['Gender_Female'].replace({True:1, False: 0})
df

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0              0            1
1    15810944   35            20000          0              0            1
2    15668575   26            43000          0              1            0
3    15603246   27            57000          0              1            0
4    15804002   19            76000          0              0            1
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1              1            0
396  15706071   51            23000          1              0            1
397  15654296   50            20000          1              1            0
398  15755018   36            33000          0              0            1
399  15594041   49            36000          1              1            0

[400 rows x 6 columns]

In [5]:
column_order = ['Age','EstimatedSalary','Gender_Male','Gender_Female','Purchased']
df=df[column_order]
df

Age  EstimatedSalary  Gender_Male  Gender_Female  Purchased
0     19            19000            1              0          0
1     35            20000            1              0          0
2     26            43000            0              1          0
3     27            57000            0              1          0
4     19            76000            1              0          0
..   ...              ...          ...            ...        ...
395   46            41000            0              1          1
396   51            23000            1              0          1
397   50            20000            0              1          1
398   36            33000            1              0          0
399   49            36000            0              1          1

[400 rows x 5 columns]

In [6]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
train,test =train_test_split(df,test_size=0.3)

In [7]:
train_X = train.iloc[:,0:4]
train_X

Age  EstimatedSalary  Gender_Male  Gender_Female
113   37            55000            1              0
215   60           108000            0              1
364   42           104000            1              0
372   39            73000            0              1
112   38            61000            1              0
..   ...              ...          ...            ...
138   28            59000            0              1
118   40            59000            1              0
105   21            72000            1              0
231   39            42000            1              0
25    47            20000            1              0

[280 rows x 4 columns]

In [8]:
train_Y = train.iloc[:,4]
train_Y

113    0
215    1
364    1
372    0
112    0
      ..
138    0
118    0
105    0
231    0
25     1
Name: Purchased, Length: 280, dtype: int64

In [9]:
test_X = test.iloc[:,0:4]
test_X

Age  EstimatedSalary  Gender_Male  Gender_Female
120   36            75000            0              1
26    49            28000            1              0
116   35            75000            1              0
228   40            72000            0              1
100   27            88000            1              0
..   ...              ...          ...            ...
19    48            29000            0              1
33    28            44000            0              1
388   47            34000            1              0
212   59            42000            0              1
98    35            73000            1              0

[120 rows x 4 columns]

In [10]:
test_Y = test.iloc[:,4]
test_Y

120    0
26     1
116    0
228    0
100    0
      ..
19     1
33     0
388    1
212    0
98     0
Name: Purchased, Length: 120, dtype: int64

In [11]:
from sklearn.svm import SVC

In [12]:
# create SVM classification obj
# linear
# kernel = linear

model_linear = SVC(kernel="linear")
model_linear.fit(train_X,train_Y)

SVC(kernel='linear')

In [13]:
pred_test_linear = model_linear.predict(test_X)
pred_test_linear

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [14]:
test_Y == pred_test_linear  # actual == predicted

120     True
26     False
116     True
228     True
100     True
       ...  
19     False
33      True
388    False
212    False
98      True
Name: Purchased, Length: 120, dtype: bool

In [15]:
np.mean(test_Y == pred_test_linear)

0.8583333333333333

In [16]:
accuracy_score(test_Y,pred_test_linear)

0.8583333333333333

In [17]:
# create SVM classification obj
# non-linear
# kernel = poly
model_poly = SVC(kernel="poly")
model_poly.fit(train_X,train_Y)

SVC(kernel='poly')

In [18]:
pred_test_poly = model_poly.predict(test_X)
pred_test_poly

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [19]:
test_Y == pred_test_poly  # actual == predicted

120     True
26     False
116     True
228     True
100     True
       ...  
19     False
33      True
388    False
212     True
98      True
Name: Purchased, Length: 120, dtype: bool

In [20]:
np.mean(test_Y == pred_test_poly)

0.7916666666666666

In [21]:
accuracy_score(test_Y,pred_test_poly)

0.7916666666666666

In [22]:
# create SVM classification obj
# non-linear
# kernel = rbf

model_rbf = SVC(kernel="rbf")
model_rbf.fit(train_X,train_Y)

SVC()

In [23]:
pred_test_rbf = model_rbf.predict(test_X)
pred_test_rbf

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [24]:
test_Y == pred_test_rbf  # actual == predicted

120     True
26     False
116     True
228     True
100     True
       ...  
19     False
33      True
388    False
212     True
98      True
Name: Purchased, Length: 120, dtype: bool

In [25]:
np.mean(test_Y == pred_test_rbf) # actual == predicted

0.8

In [26]:
accuracy_score(test_Y,pred_test_rbf)

0.8