                                        Applying the Bagging - Random Forest 

In [161]:
import pandas as pd
import numpy as np


In [162]:
df = pd.read_csv('User_Data.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [163]:
dummy_gender = pd.get_dummies(df['Gender'], prefix='Gender')

# Concatenate the dummy variables with the original DataFrame
df = pd.concat([df, dummy_gender], axis=1)

# Drop the original "Gender" column if needed
df.drop('Gender', axis=1, inplace=True)
df

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0          False         True
1    15810944   35            20000          0          False         True
2    15668575   26            43000          0           True        False
3    15603246   27            57000          0           True        False
4    15804002   19            76000          0          False         True
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1           True        False
396  15706071   51            23000          1          False         True
397  15654296   50            20000          1           True        False
398  15755018   36            33000          0          False         True
399  15594041   49            36000          1           True        False

[400 rows x 6 columns]

In [164]:
df['Gender_Male'] = df['Gender_Male'].replace({True:1, False: 0})
df['Gender_Female'] = df['Gender_Female'].replace({True:1, False: 0})
df

User ID  Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0    15624510   19            19000          0              0            1
1    15810944   35            20000          0              0            1
2    15668575   26            43000          0              1            0
3    15603246   27            57000          0              1            0
4    15804002   19            76000          0              0            1
..        ...  ...              ...        ...            ...          ...
395  15691863   46            41000          1              1            0
396  15706071   51            23000          1              0            1
397  15654296   50            20000          1              1            0
398  15755018   36            33000          0              0            1
399  15594041   49            36000          1              1            0

[400 rows x 6 columns]

In [165]:
column_order = ['Age','EstimatedSalary','Gender_Male','Gender_Female','Purchased']
df=df[column_order]
df

Age  EstimatedSalary  Gender_Male  Gender_Female  Purchased
0     19            19000            1              0          0
1     35            20000            1              0          0
2     26            43000            0              1          0
3     27            57000            0              1          0
4     19            76000            1              0          0
..   ...              ...          ...            ...        ...
395   46            41000            0              1          1
396   51            23000            1              0          1
397   50            20000            0              1          1
398   36            33000            1              0          0
399   49            36000            0              1          1

[400 rows x 5 columns]

In [166]:
colname = list(df.columns)
colname

['Age', 'EstimatedSalary', 'Gender_Male', 'Gender_Female', 'Purchased']

In [167]:
predictors=colname[:4]
predictors

['Age', 'EstimatedSalary', 'Gender_Male', 'Gender_Female']

In [168]:
target= colname[4]
target

'Purchased'

In [169]:
X=df[predictors]
X

Age  EstimatedSalary  Gender_Male  Gender_Female
0     19            19000            1              0
1     35            20000            1              0
2     26            43000            0              1
3     27            57000            0              1
4     19            76000            1              0
..   ...              ...          ...            ...
395   46            41000            0              1
396   51            23000            1              0
397   50            20000            0              1
398   36            33000            1              0
399   49            36000            0              1

[400 rows x 4 columns]

In [170]:
Y=df[target]
Y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [171]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=3,oob_score=True,n_estimators=50,criterion="entropy")

In [172]:
np.shape(df)

(400, 5)

In [173]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=50, n_jobs=3,
                       oob_score=True)

In [174]:
rf.classes_

array([0, 1], dtype=int64)

In [175]:
rf.oob_score_

0.885

In [176]:
rf.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [177]:
df['rf_pred'] = rf.predict(X)
df['rf_pred']

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: rf_pred, Length: 400, dtype: int64

In [178]:
cols = ['rf_pred','Purchased']
cols

['rf_pred', 'Purchased']

In [179]:
df["Purchased"]

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [180]:
df[cols].head()

rf_pred  Purchased
0        0          0
1        0          0
2        0          0
3        0          0
4        0          0

In [181]:
df[cols]

rf_pred  Purchased
0          0          0
1          0          0
2          0          0
3          0          0
4          0          0
..       ...        ...
395        1          1
396        1          1
397        1          1
398        0          0
399        1          1

[400 rows x 2 columns]

In [182]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(df['Purchased'],df['rf_pred'])

array([[256,   1],
       [  0, 143]], dtype=int64)

In [183]:
accuracy_score(df['Purchased'],df['rf_pred'])

0.9975

                                                    Applying ADABOOSTING 

In [184]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score

In [185]:
clf = AdaBoostClassifier(n_estimators=100)

In [186]:
clf.fit(X,Y)

AdaBoostClassifier(n_estimators=100)

In [187]:
pred = clf.predict(X)
pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,

In [188]:
clf.score(X,Y)

0.9275

In [189]:
accuracy_score(df['Purchased'],pred)

0.9275

In [190]:
clf = AdaBoostClassifier(n_estimators=100)

In [191]:
scores = cross_val_score(clf,X,Y,cv=5)

In [192]:
scores


array([0.725 , 0.9375, 0.875 , 0.8125, 0.7875])

In [193]:
scores.mean()

0.8275